name: Monitor Sites
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # Executa todo dia às 9h
jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run cotacao script
        run: python cotacao.py
